### ISSUE TITLE
control_barcode should be control_barcodes in barcode_plot.py

### ISSUE THREAD

**Issue by joshuamb** [Dowell-Lab/DAStk#21]
Lines 104 and 121 in barcode_plot.py are both
`control_bc_data = np.array(control_barcode[relevant_tf].split(';'))`
but `control_barcode` doesn't appear anywhere else in the code, and Python won't run the package because the variable is unknown. The variable `control_barcodes` is defined and I think that's the one that is supposed to be in those two lines. If I add an s to lines 104 and 121, the program runs okay.

**Comment by ignaciot** [comment]
Thanks for the notice and solution! We'll push a fix for this ASAP.

**Comment by ignaciot** [comment]
@magruca I pushed a fix to the `barcode_fix` branch, the issue was also present with the `perturbation_barcodes` variable for this new helper script. Could you guys test the different scenarios to ensure that's all? I'm about to lose connectivity but can merge and update the PyPi release later tonight.

**Comment by magruca** [comment]
Tested and good to go -- sorry this was my fault when I copied over the new file parsing code when we tweaked the md_scores.txt formatting. We can push the fix to PyPi

**Comment by ignaciot** [comment]
Changes pushed to PyPi, now v0.3.1.
