### ISSUE TITLE
Syntax Error in tf_intersect.py

### ISSUE THREAD

**Issue by andrewbcaldwell** [Dowell-Lab/DAStk#31]
After installation with pip (as well as trying cloning the repository), process_atac throws this syntax error:

```
  File "/home/DAStk_env/lib/python2.7/site-packages/DAStk-1.0.0-py2.7.egg/DAStk/tf_intersect.py", line 41
    return {**r, key: d1[key]}
             ^
SyntaxError: invalid syntax
```
Do you have any advice? Thanks!

**Comment by ignaciot** [comment]
Thanks for the report, Andrew. It looks like this syntax is likely not supported in Python 2, so the first thing I would suggest is to use it on Python 3 (either in a virtual environment, or just moving to Python 3 entirely). We've been trying to make everything as backwards-compatible as possible, but since Python 2 has been end-of-life'd this past January we may just only continue supporting Python 3. Please let me know if this took care of it!

**Comment by andrewbcaldwell** [comment]
Thanks for the update! I was under the impression that Python 2 was still required - I'll go ahead and attempt to install on Python 3.

**Comment by ignaciot** [comment]
Hey Andrew! Just checking if you got this working, before closing the issue.
