### ISSUE TITLE
Issue with atac_process

### ISSUE THREAD

**Issue by chlazaris** [Dowell-Lab/DAStk#33]
I am using two broadPeak files as input. I have specified --chromosomes as I want to ignore chrM. However, I am getting the following error. The broadPeak files look OK. I am using DAStk 1.0.0 that I installed from Bioconda using conda. Any ideas on what the issue can be here? Thank you and Happy New Year!

```
Starting --- 2023-01-09 10:16:32.505542
ATAC mean width: 746 bp (std: 388 bp). Determined an evaluation radius of 761 bp
Processing motif files in input/motifs/*
Traceback (most recent call last):
  File "/da/onc/BFx/research/lazarch2/software/anaconda3/envs/dastk_env/bin/process_atac", line 10, in <module>
    sys.exit(process_atac())
  File "/da/onc/BFx/research/lazarch2/software/anaconda3/envs/dastk_env/lib/python3.10/site-packages/DAStk/__init__.py", line 9, in process_atac
    p.main()
  File "/da/onc/BFx/research/lazarch2/software/anaconda3/envs/dastk_env/lib/python3.10/site-packages/DAStk/process_atac.py", line 262, in main
    [md_score, small_window, large_window, motif_site_count, heat] = get_md_score(filename, int(args.mp_threads), args.atac_peaks_filename, CHROMOSOMES, args.radius)
  File "/da/onc/BFx/research/lazarch2/software/anaconda3/envs/dastk_env/lib/python3.10/site-packages/DAStk/process_atac.py", line 137, in get_md_score
    sums = np.sum(results_matching_motif, axis=0)
  File "<__array_function__ internals>", line 200, in sum
  File "/da/onc/BFx/research/lazarch2/software/anaconda3/envs/dastk_env/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2324, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "/da/onc/BFx/research/lazarch2/software/anaconda3/envs/dastk_env/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (24, 4) + inhomogeneous part.
```

**Comment by mdshw5** [comment]
@chlazaris It looks like the conda recipe didn't define and specific python package versions (https://github.com/bioconda/bioconda-recipes/blob/98a09a4f229d858a514ab81b8343e27eb05e1f18/recipes/dastk/meta.yaml). The artifact on bioconda does have information about package versions on the host that built the recipe (https://anaconda.org/bioconda/dastk/1.0.0/download/noarch/dastk-1.0.0-pyh5e36f6f_0.tar.bz2), but I'm not sure that these are the same as what the authors (@ignaciot and @magruca) used at the time of publication. Maybe they can chime in?

**Comment by ignaciot** [comment]
Hi there, thanks for your patience. Have you tried installing this from pip, instead? 

The versions pointed out by @mdshw5 look fine, it's really strange that a numpy sum is what's blowing up, though. Would you be able to provide just a sample of the broadpeak files? I'd be happy to debug this, you can send them to ignacio.tripodi AT colorado.edu, along with the exact commands that you are running. Maybe I need to make some adjustments to support the current dependent library versions (it's been a few years since the last update, so this package could use a general check of all tools).

**Comment by chlazaris** [comment]
Hello @ignaciot, thank you for your response. I have just shared these by e-mail. We prefer conda to ensure reproducibility, so it would be very helpful if you could make it work with conda. Thank you in advance for your help.

**Comment by mdshw5** [comment]
@ignaciot Thanks for the response. It would be helpful if you could post a list of the last known working versions of the python dependencies. I just checked the PyPI archive and it contains the same information that's in your `setup.py`:

```python
    install_requires=[
        'argparse',
        'datetime',
        'numpy',
        'matplotlib',
        'adjustText',
        'scipy',
        'pandas',
        'pybedtools',
        'futures',
        'scikit-learn',
        'networkx>=2',
        'upsetplot',
    ],
```

Without min/max semantic versions you have a high probability of breaking changes even in packages such as numpy.

**Comment by ignaciot** [comment]
The issue was with a numpy feature that was deprecated. I have pushed a fix to the repo and generated a new PyPi version for it (so you can upgrade from pip), that will work with newer versions of numpy and will prevent the error you mentioned above. 

Unfortunately I don't have the time to mess with the bioconda package at the moment, but feel free to make a pull request if you'd like to help. 

These are the versions of the libraries I'm using which seem to work fine:

    numpy==1.21.6
    matplotlib==3.5.1
    matplotlib-venn==0.11.7
    adjustText==0.7.3
    scipy==1.8.0
    pybedtools==0.9.0
    futures==3.0.5
    scikit-learn==1.0.2
    networkx==2.7.1
    UpSetPlot==0.8.0

**Comment by mdshw5** [comment]
Thanks @ignaciot. It looks like the bioconda build is failing (https://github.com/bioconda/bioconda-recipes/pull/39028), but I can follow up and figure out what needs to be done. We really appreciate your effort putting out a new release with this fix!

**Comment by chlazaris** [comment]
Thank you very much @ignaciot  and @mdshw5 for your help!

**Comment by ignaciot** [comment]
Sure thing! Thanks for reporting this, and I'll be happy to merge in the necessary changes to get the bioconda recipe working!

**Comment by chlazaris** [comment]
Thank you very much, Ignacio!

Best Regards,

Harris

**Comment by mdshw5** [comment]
I've updated the bioconda recipe in https://github.com/bioconda/bioconda-recipes/pull/39064. It looks like the build will complete, so as long as tests pass this will be merged into bioconda shortly.

**Comment by chlazaris** [comment]
Thank you very much, Matt!

**Comment by mdshw5** [comment]
It looks like the `license_file` directive requires that a **copy** of the LICENSE be committed to the bioconda recipes repo. Since it looks like this is an unmodified BSD3 license, I've removed this directive. @ignaciot please let me know if this is okay with you. Your LICENSE file will still be redistributed as part of the bioconda package, so this complies with the BSD license terms.

**Comment by ignaciot** [comment]
Thanks for checking, this makes sense and is perfectly fine with me.
