### ISSUE TITLE
Not able to generate MA plot and Barcode Plot

### ISSUE THREAD

**Issue by Divya6805** [Dowell-Lab/DAStk#35]
![Screenshot 2023-11-24 181423](https://github.com/Dowell-Lab/DAStk/assets/151932729/ecfce676-ba2a-46ce-a342-042d803d0ddc)
command previously used: 
python3 differential_md_score.py -1 FL1_CD4thy_peaks_sorted_md_scores.txt -2 KO1_CD4thy_peaks_sorted_md_scores.txt -m FL1_CD4thy -n KO1_CD4thy -b -o /common/accounts/divyas/Prerana/ATAC/DAStk/diff_md_score/FL1_CD4_KO1_CD4_diff_md -t 6 -g

The differential md score file is generated but the MA plots and Barcode plot command is giving a Index out of range error in adjustText as shown in the screenshot. Please help!

**Comment by ignaciot** [comment]
Looking at the code, this is likely because none of the motifs have a p-value below the standard cutoff (it defaults to `0.00001`). You can pass your own cutoff with the `-p` argument (see `python3 differential_md_score.py --help`).

The error message should be more specific to this scenario, I'll push a fix to fail more gracefully when this happens.

**Comment by Divya6805** [comment]
Yes, I realised that. Thank you so much !

Best,
Divya

**Comment by ignaciot** [comment]
Closing this issue, the tool now displays an error message if none of the TF motifs result in a significant difference in activity (none scores below the default or given p-value threshold).
